### ISSUE TITLE
Is it possible to use the library in a distributed system integrated with a message broker as redis or rabbitmq? 

### ISSUE THREAD

**Issue by antunesleo** [Mulugruntz/celery-pubsub#101]
I would like to run one or more celery instances (services) and publish event to subscribers that can have more than 1 instances e.g: the subscriber1 has two different services listening to the event, while the subscriber2 has three of them. Is it possible or the intent of library is to be used inside only 1 celery instance/service?

I've tried to implement the idea but got stuck: https://github.com/antunesleo/celery-pubsub-example

Would be great to use this library that way, it would spare a lot of time/work

**Comment by jerryvurbl** [comment]
just a lurker but i suspect your subscribers need to "celery = Celery(..." instead of "worker = Celery(..."

**Comment by Mulugruntz** [comment]
@antunesleo Did @jerryvurbl 's answer help you?
