### ISSUE TITLE
Better dependencies

### ISSUE THREAD

**Issue by Mulugruntz** [Mulugruntz/celery-pubsub#127]
This is a library and should have more flexible requirements.
Should give guarantees: if version is at least xxx, then it will work.

Because currently, the build is broken on several Python versions.

And remove pyup as well.

**Comment by lullis** [comment]
Any chance a new release can be published on PyPI with the more relaxed dependencies?

**Comment by Mulugruntz** [comment]
Hi @lullis 

Sorry for taking so long for basic things. I've been quite busy for many months. I'll try to do that before the end of January 2022 (still no promise). But of course, if you want to submit a PR, that's very welcome.

**Comment by Mulugruntz** [comment]
Hi @lullis 
I pushed 1.0.0. Please tell me if everything is fine.
I reused a branch I created 6 months ago but never merged until now. I might reuse some elements of your solution in some future.
