### ISSUE TITLE
failed installing package celery_pubsub==0.1.7

### ISSUE THREAD

**Issue by adrianbr** [Mulugruntz/celery-pubsub#7]
adr@ubuntu:~$ pip install celery_pubsub
Collecting celery_pubsub
  Downloading celery-pubsub-0.1.7.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-mLsH7V/celery-pubsub/setup.py", line 61, in <module>
        install_requires=install_requires(),
      File "/tmp/pip-build-mLsH7V/celery-pubsub/setup.py", line 19, in install_requires
        return [_strip_comments(req) for req in codecs.open('requirements.txt', 'r', 'utf-8').readlines() if req]
      File "/usr/lib/python2.7/codecs.py", line 896, in open
        file = __builtin__.open(filename, mode, buffering)
    IOError: [Errno 2] No such file or directory: 'requirements.txt'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-mLsH7V/celery-pubsub/

Can reproduce on a variety of environments (docker, ubuntu, windows)

**Comment by Mulugruntz** [comment]
From a freshly new virtualenv (py 2.7):
```python
pip install celery-pubsub                                                                             1s  ●  ~/P/celery-pubsub 
Collecting celery-pubsub
  Downloading celery-pubsub-0.1.8.tar.gz
Collecting celery~=4.1.0 (from celery-pubsub)
  Using cached celery-4.1.0-py2.py3-none-any.whl
Collecting vine~=1.1.4 (from celery-pubsub)
  Using cached vine-1.1.4-py2.py3-none-any.whl
Collecting kombu~=4.1.0 (from celery-pubsub)
  Using cached kombu-4.1.0-py2.py3-none-any.whl
Collecting billiard~=3.5.0 (from celery-pubsub)
Collecting pytz>dev (from celery~=4.1.0->celery-pubsub)
  Using cached pytz-2017.3-py2.py3-none-any.whl
Collecting amqp<3.0,>=2.1.4 (from kombu~=4.1.0->celery-pubsub)
  Using cached amqp-2.2.2-py2.py3-none-any.whl
Building wheels for collected packages: celery-pubsub
  Running setup.py bdist_wheel for celery-pubsub ... done
  Stored in directory: /home/sgiffard/.cache/pip/wheels/39/18/18/10b2b3e4edf11bcad00b9e99bfbc0248a1f2884b72572e56d4
Successfully built celery-pubsub
Installing collected packages: pytz, billiard, vine, amqp, kombu, celery, celery-pubsub
Successfully installed amqp-2.2.2 billiard-3.5.0.3 celery-4.1.0 celery-pubsub-0.1.8 kombu-4.1.0 pytz-2017.3 vine-1.1.4
```

**Comment by Mulugruntz** [comment]
:+1:
